export const SEARCH_REPOS = 'SEARCH_REPOS';
export const SEARCH_REPOS_OPTIONS = 'SEARCH_REPOS_OPTIONS';
export const RESET_REPOS = 'RESET_REPOS';

export const GET_REPO = 'GET_REPO';
export const CLEAR_REPO = 'CLEAR_REPO';

export const SET_TOKEN = 'SET_TOKEN';
export const GET_TOKEN = 'GET_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';

export const SET_ELAPSED_DELEGATIONS = 'SET_ELAPSED_DELEGATIONS';
export const SET_ELAPSED_TIME = 'SET_ELAPSED_TIME';
export const RESET_ELAPSED_TIME = 'RESET_ELAPSED_TIME';